Feature/2
AgainIoT/Open-Set-Go_client pull request #8
Opened 2023-08-16 13:10 UTC by hummingbbird

## Describe changes

Create markdown editor component

## Issue number or link
#2 

## Types of changes

What is the type of code change?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (changes that resolve errors)
- [x] New feature (changes which adds functionality)
- [ ] Breaking change (big changes that affect existing functionality)
- [ ] Documentation Update

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have read the "README.md"
- [ ] My code follows the style guidelines of this project
- [ ] My changes generate no new warnings
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

2023-08-16 13:13 UTC, sinji2102 approved these changes

2023-08-16 13:13 UTC, sinji2102 commented on src/components/common/MarkdownPreview.js
> +export default MarkdownPreview;
👍

2023-08-16 13:13 UTC, sinji2102 commented on src/components/common/MarkdownPreview.js
> +const MarkdownPreview = () => {
👍

2023-08-17 01:44 UTC, ymw0407 commented on package-lock.json
지금 여기서 발생한 문제는 npm과 yarn을 혼용하여서 발생한 문제로 보입니다.
기존에는 yarn을 사용하도록 하였기 때문에 yarn.lock 파일을 통해서 패키지들의 버전을 관리할 수 있었습니다.
하지만, 지금 package-lock.json 파일이 생기고, 그게 여러 버전이 생긴 것으로 보아 초기에 yarn으로 버전관리를 하였으나 나중에 각자가 npm install을 통해서 다른 모듈을 설치하는 과정에서 여러 버전으로 설치되었고 그 결과 충돌이 난것 같습니다
---
결론적으로, 현재 yarn package manager를 사용하는데에 있어서 특별한 문제가 없다면, package-lock.josn을 삭제하고, yarn으로만 관리하면 될것 같습니다. 만약, yarn.lock에서도 이와 같은 문제가 발생한다면 같은 모듈을 각자 따로 설치하여 충돌이 난 것으로 생각하시면 됩니다.

2023-08-17 01:46 UTC, ymw0407 requested changes
특별한 문제가 없다면 yarn으로 모든 패키지를 관리하고, package-lock.json을 삭제하는 것을 권고합니다.
항상 패키지 설치는 npm install이 아닌 yarn install을 사용해주세요...
@sinji2102 @hummingbbird @ancy0

2023-08-17 06:47 UTC, ymw0407 commented
@hummingbbird @ancy0 돌아가는지 한번 확인 부탁드립니다.

2023-08-17 06:48 UTC, ymw0407 approved these changes

2023-08-17 10:55 UTC, merged